#!/bin/bash
## check_unicorn.sh for check_unicorn in /Users/fresh/nagios/check_unicorn
##
## Made by Anthony Scalisi
## <scalisi.a@gmail.com>
##
## Started on  Mon May 28 15:25:47 2012 Anthony Scalisi
## Last update Mon May 28 16:59:28 2012 Anthony Scalisi
##

OK_STATE=0
WARNING_STATE=1
CRITICAL_STATE=2
UNKNOWN_STATE=3
EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
    echo "Usage: `basename $0` [number of workers expected]"
    exit ${UNKNOWN_STATE}
    exit $E_BADARGS
fi

if [ "$(id -u)" != "0" ]; then
    echo ""
    echo "Gotta be root to run this script (or Obiwan Kenobi)."
    echo ""
    echo "Syntax: sudo $0"
    echo ""
    exit 42
fi

check_master=`sudo ps awx | grep 'unicorn_rails master' | grep -v grep`
check_workers=`sudo ps awx | grep 'unicorn_rails worker' | grep -v grep`

count_master=`sudo ps awx | grep 'unicorn_rails master' | grep -v grep | wc -l`
count_workers=`sudo ps awx | grep 'unicorn_rails worker' | grep -v grep | wc -l`

check_all=`sudo ps awx | grep unicorn | grep -v grep`
count_all=`sudo ps awx | grep unicorn | grep -v grep | wc -l`

if [[ "$count_master" -eq 1 ]]; then
        if [[ "$count_workers" -eq "$1" ]]; then
                echo "OK - $count_workers unicorn workers running"
                exit ${OK_STATE}
        else
                if [[ "$count_workers" -gt "$1" ]]; then
                        echo "WARNING - Too many unicorn workers ($count_workers) running."
                        exit ${WARNING_STATE}
                elif [[ "$count_workers" -lt $1 ]]; then
                        echo "CRITICAL - only $count_workers unicorn workers are running !"
                        exit ${CRITICAL_STATE}
                fi
        fi
elif [[ "$count_master" -gt 1 ]]; then
    echo "WARNING - $count_master master unicorn running at the same time!"
    exit ${WARNING_STATE}
elif [[ "$count_master" -lt 1 ]]; then
    echo "CRITICAL - no master unicorn running !"
    exit ${CRITICAL_STATE}
else
    echo "UNKNOWN - Could not figure unicorn status. Please check it out ASAP."
    exit ${UNKNOW_STATE}
fi